apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      version: '24.0.4'
      sourceRef:
        name: bitnami
        kind: HelmRepository
  interval: 1m
  install:
    disableWait: true
    disableWaitForJobs: true
    crds: CreateReplace
    timeout: 5m
  upgrade:
    disableWait: true
    disableWaitForJobs: true
    crds: CreateReplace
    timeout: 5m
  values:
    auth:
      adminUser: admin
      adminPassword: admin
    initContainers:
      - name: kubernetes-authenticator
        image: ghcr.io/chr-fritz/keycloak-kubernetes-authenticator:dev-main
        imagePullPolicy: Always
        volumeMounts:
          - name: providers
            mountPath: /opt/keycloak/providers
            readOnly: false
      - name: truststore-creator
        image: ghcr.io/chr-fritz/java-trust-store-builder:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: truststore
            mountPath: /truststore
            readOnly: false
          - name: ca-certificates
            mountPath: /ca-certs
            readOnly: true
    proxy: edge
    extraEnvVars:
      - name: KEYCLOAK_SPI_TRUSTSTORE_FILE
        value: /truststore/truststore.jks
      - name: KEYCLOAK_SPI_TRUSTSTORE_PASSWORD
        value: changeit
      - name: KEYCLOAK_SPI_TRUSTSTORE_FILE_HOSTNAME_VERIFICATION_POLICY
        value: ANY
      - name: KC_HOSTNAME_URL
        value: https://keycloak-192-168-107-4.nip.io
    ingress:
      enabled: true
      hostname: keycloak-192-168-107-4.nip.io
      tls: true
      selfSigned: true
    extraStartupArgs: "--debug"
    extraVolumeMounts:
      - name: truststore
        mountPath: /truststore
        readOnly: true
      - name: providers
        mountPath: /opt/bitnami/keycloak/providers
        readOnly: true
    extraVolumes:
      - name: providers
        emptyDir: { }
      - name: truststore
        emptyDir: { }
      - name: ca-certificates
        projected:
          sources:
            - configMap:
                name: kube-root-ca.crt
                items:
                  - key: ca.crt
                    path: k8s-ca.crt
