apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chart:
    spec:
      chart: keycloakx
      sourceRef:
        name: codecentric
        kind: HelmRepository
  interval: 1m
  install:
    disableWait: true
    disableWaitForJobs: true
    crds: CreateReplace
    timeout: 5m
  upgrade:
    disableWait: true
    disableWaitForJobs: true
    crds: CreateReplace
    timeout: 5m
  values:
    image:
      tag: "26.4"
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "start"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "--debug"
    extraInitContainers: |
      - name: truststore-creator
        image: ghcr.io/chr-fritz/java-trust-store-builder:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: truststore
            mountPath: /truststore
            readOnly: false
          - name: ca-certificates
            mountPath: /ca-certs
            readOnly: true
    extraEnv: |
      - name: KEYCLOAK_SPI_TRUSTSTORE_FILE
        value: /truststore/truststore.jks
      - name: KEYCLOAK_SPI_TRUSTSTORE_PASSWORD
        value: changeit
      - name: KEYCLOAK_SPI_TRUSTSTORE_FILE_HOSTNAME_VERIFICATION_POLICY
        value: ANY
      - name: KC_HOSTNAME_URL
        value: http://keycloak-192-168-107-4.nip.io
      - name: KC_BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
        value: admin
      - name: KC_FEATURES
        value: account-api,admin-api,authorization,ciba,client-policies,device-flow,dpop,impersonation,opentelemetry,organization,par,passkeys,persistent-user-sessions,recovery-codes,step-up-authentication,update-email,user-event-metrics,web-authn,client-auth-federated,kubernetes-service-accounts
    ingress:
      enabled: true
      hostname: keycloak-192-168-107-4.nip.io
      rules:
        - # Ingress host
          host: 'keycloak-192-168-107-4.nip.io'
          # Paths for the host
          paths:
            - path: '/auth/'
              pathType: Prefix
    extraVolumeMounts: |
      - name: truststore
        mountPath: /truststore
        readOnly: true
    extraVolumes: |
      - name: truststore
        emptyDir: { }
      - name: ca-certificates
        projected:
          sources:
            - configMap:
                name: kube-root-ca.crt
                items:
                  - key: ca.crt
                    path: k8s-ca.crt
